server:
  port: 8090
aws:
  access_key_id: ""
  secret_access_key: ""
  s3:
    region: us-west-2
    bucket: edxsample
spring:
  datasource:
    url: jdbc:mysql://edx-photos-db.cxgrmb0mgtup.us-west-2.rds.amazonaws.com:3306/edx?autoReconnect=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: Domek123
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
     ddl-auto: create

# File size limit
multipart:
  maxFileSize: 4Mb
  maxRequestSize: 4Mb

